/**
 * Basic 5–6 maths topics the pack was missing.
 *
 * Written against the **Lagos State Unified Scheme of Work for Primary
 * Schools, 2021 Edition** (Mathematics, Primary 4–6) — the state's own
 * curriculum document, which follows the NERDC national curriculum. Only the
 * topic list and its sequence come from there: what a class is taught in which
 * term is a curriculum fact. Every question below is generated by us.
 *
 * A coverage count made the gap plain: Basic 6 had a single maths skill and
 * Basic 5 had five, against fifty-one for Basic 3. A product that says "Basic
 * 1 to 6" cannot have almost nothing for the last two classes, and those are
 * the years common entrance is actually sat in.
 *
 * The scheme's own ordering, for anyone extending this:
 *
 *   Primary 5, Term 3  wk 1  Temperature — Celsius, Fahrenheit, Kelvin
 *                      wk 2  Lines and angles — complementary, supplementary
 *   Primary 6, Term 1  wk 11 Measures of central tendency, probability
 *   Primary 6, Term 2  wk 5  LCM and HCF, to three digits
 *                            Division, including decimals
 */

import type { Item, SkillDef } from '../../../engine/types'
import { entry, mc, tapMany } from '../../shared/authoring'

const gcd = (a: number, b: number): number => (b === 0 ? a : gcd(b, a % b))
const lcmOf = (a: number, b: number): number => (a * b) / gcd(a, b)

/** Mean of a whole-number list, kept exact so the answer is never a decimal. */
const meanOf = (xs: number[]): number => xs.reduce((s, x) => s + x, 0) / xs.length

const medianOf = (xs: number[]): number => {
  const s = [...xs].sort((a, b) => a - b)
  const mid = s.length >> 1
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2
}

/* ------------------------------------------------------------------ *
 * Number — LCM and HCF
 * ------------------------------------------------------------------ */

const lcmHcf: SkillDef = {
  id: 'ng.maths.number.lcm-hcf',
  title: 'LCM and HCF',
  yearBand: 'b6',
  prerequisites: ['ng.maths.number.factors'],
  concepts: ['lcm-hcf'],
  hint: 'HCF is the biggest number that divides into both. LCM is the smallest number both divide into.',
  helpAtHome:
    'Two buses leave at different intervals — when do they next leave together? That is the LCM, and it is the question this topic is really asking.',
  generate: ({ rng, difficulty }): Item => {
    /*
     * Built from two small factors and a shared one rather than picked at
     * random, so the HCF is never 1 and the LCM never runs to five digits —
     * both of which make the question either trivial or unreasonable.
     */
    const shared = rng.pick([[2, 3, 4], [2, 3, 4, 6], [3, 4, 6, 8], [4, 6, 8, 9], [6, 8, 9, 12]][difficulty - 1])
    const p = rng.int(2, [4, 5, 6, 7, 9][difficulty - 1])
    let q = rng.int(2, [4, 5, 6, 7, 9][difficulty - 1])
    if (q === p) q = p === 2 ? 3 : p - 1
    const a = shared * p
    const b = shared * q

    const variant = rng.int(1, 3)

    if (variant === 1) {
      const answer = gcd(a, b)
      // Distractors a child would actually reach for: the LCM, one of the
      // numbers, and a common factor that is not the highest.
      const smallerCommon = [...Array(answer).keys()].map((i) => i + 1).filter((f) => answer % f === 0 && f !== answer)
      return mc(
        rng,
        `What is the highest common factor (HCF) of ${a} and ${b}?`,
        answer,
        [lcmOf(a, b), Math.min(a, b), smallerCommon.length ? rng.pick(smallerCommon) : answer + 1],
        {
          explanation: `${answer} divides into both ${a} and ${b}, and nothing bigger does.`,
        },
      )
    }

    if (variant === 2) {
      const answer = lcmOf(a, b)
      return mc(
        rng,
        `What is the lowest common multiple (LCM) of ${a} and ${b}?`,
        answer,
        [a * b, gcd(a, b), answer + Math.min(a, b)],
        {
          explanation:
            a * b === answer
              ? `${a} and ${b} share no factor above 1, so the LCM is ${a} × ${b} = ${answer}.`
              : `${answer} is the smallest number both ${a} and ${b} divide into.`,
        },
      )
    }

    /* The real-life shape the scheme asks for. */
    const answer = lcmOf(a, b)
    return entry(
      `One tap drips every ${a} seconds. Another drips every ${b} seconds.\nThey drip together now. After how many seconds do they next drip together?`,
      answer,
      {
        maxDigits: 4,
        suffix: 'seconds',
        explanation: `The lowest common multiple of ${a} and ${b} is ${answer}.`,
      },
    )
  },
}

/* ------------------------------------------------------------------ *
 * Data — mean, median, mode and probability
 * ------------------------------------------------------------------ */

const centralTendency: SkillDef = {
  id: 'ng.maths.data.central-tendency',
  title: 'Mean, median and mode',
  yearBand: 'b6',
  prerequisites: ['ng.maths.data.average'],
  concepts: ['central-tendency'],
  hint: 'Mode is the one that appears most. Median is the middle after sorting. Mean is the total shared out.',
  helpAtHome:
    'Take the ages of everyone in the house and work out all three. Which one best describes the family, and why?',
  generate: ({ rng, difficulty }): Item => {
    const count = [5, 5, 7, 7, 9][difficulty - 1]
    const top = [10, 12, 15, 20, 30][difficulty - 1]

    const which = rng.pick(['mode', 'median', 'mean'] as const)

    if (which === 'mode') {
      /* Build one clear winner, or the question has no single answer. */
      const winner = rng.int(1, top)
      const others: number[] = []
      while (others.length < count - 3) {
        const v = rng.int(1, top)
        if (v !== winner && !others.includes(v)) others.push(v)
      }
      const list = rng.shuffle([winner, winner, winner, ...others])
      return mc(rng, `What is the mode of these numbers?\n${list.join(', ')}`, winner, [
        medianOf(list),
        Math.max(...list),
        Math.min(...list),
      ], { explanation: `${winner} appears three times — more often than any other number.` })
    }

    if (which === 'median') {
      /* Odd count only, so the median is a member of the list. */
      const n = count % 2 ? count : count + 1
      const list: number[] = []
      while (list.length < n) {
        const v = rng.int(1, top)
        if (!list.includes(v)) list.push(v)
      }
      const answer = medianOf(list)
      const sorted = [...list].sort((a, b) => a - b)
      /*
       * The mean is the mistake worth offering, but it is almost never a whole
       * number — printed raw it arrives as 6.428571428571429, which is
       * unreadable and tells a child at a glance which option to avoid.
       */
      const nearMean = Math.round(meanOf(list))
      return mc(rng, `What is the median of these numbers?\n${list.join(', ')}`, answer, [
        nearMean,
        sorted[0],
        sorted[sorted.length - 1],
      ], {
        explanation: `In order: ${sorted.join(', ')}. The middle one is ${answer}.`,
      })
    }

    /*
     * Mean, exact by construction.
     *
     * Built as `target` repeated, then nudged in +d/−d pairs so the total is
     * always exactly target × n. The obvious alternative — scatter n−1 values
     * and make the last one absorb the difference — can drive that last value
     * below 1, and clamping it there silently breaks the arithmetic: the
     * stated answer stops matching the list, and a child who works it out
     * properly is marked wrong. A whole-number mean also keeps this a question
     * about averaging rather than about dividing.
     */
    const n = count
    const target = rng.int(4, top)
    const list = Array.from({ length: n }, () => target)
    const spread = Math.min(3, target - 1)
    for (let i = 0; i + 1 < n; i += 2) {
      const d = rng.int(0, spread)
      list[i] += d
      list[i + 1] -= d
    }
    const shown = rng.shuffle(list)
    const total = shown.reduce((s, x) => s + x, 0)
    return entry(`What is the mean of these numbers?\n${shown.join(', ')}`, target, {
      maxDigits: 3,
      explanation: `They add up to ${total}. ${total} ÷ ${n} = ${target}.`,
    })
  },
}

const probability: SkillDef = {
  id: 'ng.maths.data.probability',
  title: 'Chance and probability',
  yearBand: 'b6',
  prerequisites: ['ng.maths.fractions.of-set'],
  concepts: ['probability'],
  hint: 'Probability is: how many ways it can happen, out of how many things there are altogether.',
  helpAtHome:
    'Before rolling a die, ask what is more likely — an even number, or a six? Getting the reasoning right matters more than the fraction.',
  generate: ({ rng, difficulty }): Item => {
    const variant = rng.int(1, 3)

    if (variant === 1) {
      /* Certain / impossible / likely — the language before the arithmetic. */
      const cases = [
        ['The sun will rise tomorrow.', 'Certain'],
        ['A rolled die shows 7.', 'Impossible'],
        ['A tossed coin shows heads.', 'Even chance'],
        ['A rolled die shows a number less than 7.', 'Certain'],
        ['A rolled die shows an even number.', 'Even chance'],
        ['You pick a red ball from a bag of only blue balls.', 'Impossible'],
      ] as const
      const [statement, answer] = rng.pick(cases as unknown as (readonly [string, string])[])
      return mc(rng, `How likely is this?\n${statement}`, answer, ['Certain', 'Impossible', 'Even chance'].filter((o) => o !== answer), {
        explanation: `This one is ${answer.toLowerCase()}.`,
      })
    }

    if (variant === 2) {
      const top = [3, 4, 5, 6, 8][difficulty - 1]
      const wanted = rng.int(1, top)
      const rest = rng.int(1, top)
      const total = wanted + rest
      const d = gcd(wanted, total)
      const answer = `${wanted / d}/${total / d}`

      /*
       * Every distractor has to be a proper fraction. A probability above 1 is
       * not a mistake a child could believe — it is a nonsense option that
       * gives the answer away, and the smoke test rejects them outright. These
       * are the errors actually made: reading off the other colour, and
       * miscounting the total.
       *
       * Deliberately NOT the unreduced form of the answer. 2/4 offered beside
       * 1/2 is not a distractor — it is a second correct option, and marking a
       * child wrong for picking it would be indefensible.
       */
      const rd = gcd(rest, total)
      const wrong = [
        `${rest / rd}/${total / rd}`,
        wanted > 1 ? `${wanted - 1}/${total}` : `${wanted}/${total + 1}`,
        `${wanted}/${total + rest}`,
      ].filter((c) => c && c !== answer)

      const [colour, other] = rng.shuffle(['red', 'blue', 'green', 'yellow', 'white']).slice(0, 2)
      const item = rng.pick(['balls', 'marbles', 'beads', 'counters'])
      return mc(
        rng,
        `A bag holds ${wanted} ${colour} ${item} and ${rest} ${other} ${item}.\nWhat is the probability of picking a ${colour} one?`,
        answer,
        wrong,
        { explanation: `${wanted} ${colour} out of ${total} ${item} altogether: ${answer}.` },
      )
    }

    /* Which outcomes satisfy the event — checks understanding, not division. */
    const target = rng.pick(['an even number', 'a number greater than 4', 'a number less than 3'] as const)
    const faces = [1, 2, 3, 4, 5, 6]
    const hit = (n: number) =>
      target === 'an even number' ? n % 2 === 0 : target === 'a number greater than 4' ? n > 4 : n < 3
    return tapMany(
      rng,
      `A die is rolled. Tap every face that gives ${target}.`,
      faces.map((f) => ({ value: f, correct: hit(f) })),
      { explanation: `${faces.filter(hit).join(', ')} — that is ${faces.filter(hit).length} of the 6 faces.` },
    )
  },
}

/* ------------------------------------------------------------------ *
 * Measurement — temperature
 * ------------------------------------------------------------------ */

const temperature: SkillDef = {
  id: 'ng.maths.measure.temperature',
  title: 'Temperature',
  yearBand: 'b5',
  prerequisites: ['ng.maths.measure.mass'],
  concepts: ['temperature'],
  hint: 'To go from °C to °F: multiply by 9, divide by 5, then add 32.',
  helpAtHome:
    'Nigerian weather forecasts use Celsius and some recipes use Fahrenheit — converting a real one makes the formula stick.',
  generate: ({ rng, difficulty }): Item => {
    const variant = rng.int(1, 3)

    if (variant === 1) {
      /* Multiples of 5 only, so °F stays a whole number. */
      const c = rng.step(5, [30, 40, 50, 60, 100][difficulty - 1], 5)
      const f = (c * 9) / 5 + 32
      return entry(`Convert ${c}°C to degrees Fahrenheit.`, f, {
        maxDigits: 3,
        suffix: '°F',
        explanation: `(${c} × 9 ÷ 5) + 32 = ${(c * 9) / 5} + 32 = ${f}°F.`,
      })
    }

    if (variant === 2) {
      const c = rng.step(5, [40, 50, 60, 80, 100][difficulty - 1], 5)
      return entry(`Convert ${c}°C to Kelvin.`, c + 273, {
        maxDigits: 4,
        suffix: 'K',
        explanation: `K = °C + 273, so ${c} + 273 = ${c + 273}K.`,
      })
    }

    if (rng.chance(0.5)) {
      /* Fahrenheit back to Celsius — the scheme asks for both directions. */
      const c = rng.step(5, [40, 50, 60, 80, 100][difficulty - 1], 5)
      const f = (c * 9) / 5 + 32
      return entry(`Convert ${f}°F to degrees Celsius.`, c, {
        maxDigits: 3,
        suffix: '°C',
        explanation: `(${f} − 32) × 5 ÷ 9 = ${f - 32} × 5 ÷ 9 = ${c}°C.`,
      })
    }

    const c = rng.step(5, [35, 45, 60, 80, 95][difficulty - 1], 5)
    const f = (c * 9) / 5 + 32
    const place = rng.pick(['Kano', 'Jos', 'Lagos', 'Enugu', 'Ibadan', 'Abuja'])
    return mc(
      rng,
      `${place} is ${c}°C today. Which of these is the same temperature?`,
      `${f}°F`,
      [`${c + 32}°F`, `${(c * 9) / 5}°F`, `${Math.round((c * 5) / 9 + 32)}°F`],
      { explanation: `Multiply by 9, divide by 5, then add 32: ${f}°F.` },
    )
  },
}

/* ------------------------------------------------------------------ *
 * Shape — complementary and supplementary angles
 * ------------------------------------------------------------------ */

const anglePairs: SkillDef = {
  id: 'ng.maths.shapes.angle-pairs',
  title: 'Angles that go together',
  yearBand: 'b5',
  prerequisites: ['ng.maths.shapes.angle-types'],
  concepts: ['complementary-supplementary'],
  hint: 'Complementary angles add up to 90°. Supplementary angles add up to 180°.',
  helpAtHome: 'A corner of a page is 90° and a straight edge is 180° — the two facts the whole topic rests on.',
  generate: ({ rng, difficulty }): Item => {
    const kind = rng.chance(0.5) ? 'complementary' : 'supplementary'
    const whole = kind === 'complementary' ? 90 : 180
    const step = [10, 10, 5, 5, 1][difficulty - 1]
    const angle = rng.step(step, whole - step, step)
    const answer = whole - angle

    if (rng.chance(0.6)) {
      return entry(`Two ${kind} angles add up to ${whole}°.\nOne is ${angle}°. What is the other?`, answer, {
        maxDigits: 3,
        suffix: '°',
        explanation: `${whole} − ${angle} = ${answer}°.`,
      })
    }

    const other = whole - angle
    return mc(
      rng,
      `${angle}° and ${other}° are ${whole === 90 ? 'complementary' : 'supplementary'} — is that right, and why?`,
      `Yes — they add up to ${whole}°`,
      [
        `No — they add up to ${whole === 90 ? 180 : 90}°`,
        'Yes — because both are acute',
        'No — angles are never added',
      ],
      { explanation: `${angle} + ${other} = ${whole}, and ${whole}° is what ${kind} angles make.` },
    )
  },
}

export const b6NumberSkills: SkillDef[] = [lcmHcf]
export const b6DataSkills: SkillDef[] = [centralTendency, probability]
export const b5MeasureSkills: SkillDef[] = [temperature]
export const b5ShapeSkills: SkillDef[] = [anglePairs]
