/**
 * Curated sentence banks for the English Grammar pack.
 *
 * Word banks generate; sentences with meaning have to be written. Everything
 * here is a fill-in-the-gap or classify-this item where the distractors were
 * chosen by hand, because that is the only way to guarantee the rule the
 * brief insists on: if two answers could be defended, the item is wrong.
 *
 * Each entry therefore carries its own `wrong` list. No distractor is ever
 * generated by shuffling the other correct answers in the bank.
 */

import type { Tier } from './words'

export interface Cloze {
  /** Uses "____" for the gap. */
  text: string
  answer: string
  wrong: string[]
  tier: Tier
  /** Teaches the rule, not just the answer. */
  why: string
}

const cz = (text: string, answer: string, wrong: string[], tier: Tier, why: string): Cloze =>
  ({ text, answer, wrong, tier, why })

/* ------------------------------------------------------------------ *
 * Sentence types
 * ------------------------------------------------------------------ */

export type SentenceKind = 'statement' | 'question' | 'command' | 'exclamation'

export interface TypedSentence {
  /** No end mark — the punctuation skill adds it, the type skill asks for it. */
  text: string
  kind: SentenceKind
  tier: Tier
}

const ts = (text: string, kind: SentenceKind, tier: Tier): TypedSentence => ({ text, kind, tier })

export const TYPED_SENTENCES: TypedSentence[] = [
  ts('Ada is eating her rice', 'statement', 1),
  ts('The goat ran into the compound', 'statement', 1),
  ts('My father works in Kano', 'statement', 1),
  ts('We have three new textbooks', 'statement', 1),
  ts('The bus left at six o’clock', 'statement', 2),
  ts('Musa can swim very well', 'statement', 1),
  ts('Our teacher gave us homework', 'statement', 2),
  ts('It is raining outside', 'statement', 1),
  ts('Chidi keeps his biros in a pencil case', 'statement', 2),
  ts('The mangoes in that basket are ripe', 'statement', 2),
  ts('Halima lives near the market', 'statement', 1),
  ts('The generator stopped working last night', 'statement', 3),
  ts('Where is my pencil', 'question', 1),
  ts('What is your name', 'question', 1),
  ts('Who took my ruler', 'question', 1),
  ts('Are you coming to school tomorrow', 'question', 1),
  ts('How many oranges did she buy', 'question', 2),
  ts('Why is the gate locked', 'question', 2),
  ts('When does the match start', 'question', 2),
  ts('Is this your bag', 'question', 1),
  ts('Did Chidi finish his work', 'question', 2),
  ts('Can I borrow your biro', 'question', 1),
  ts('Whose uniform is on the bench', 'question', 3),
  ts('Close the door', 'command', 1),
  ts('Please sit down', 'command', 1),
  ts('Wash your hands before eating', 'command', 2),
  ts('Bring me the broom', 'command', 1),
  ts('Do not run in the corridor', 'command', 2),
  ts('Line up quietly', 'command', 2),
  ts('Open your textbook to page ten', 'command', 2),
  ts('Sweep the classroom before you go', 'command', 3),
  ts('Put your sandals under the bed', 'command', 2),
  ts('What a big goat that is', 'exclamation', 1),
  ts('How cold this water is', 'exclamation', 2),
  ts('What a lovely surprise this is', 'exclamation', 2),
  ts('How fast that lorry is going', 'exclamation', 2),
  ts('What a mess this room is', 'exclamation', 2),
  ts('How kind you are', 'exclamation', 1),
  ts('What a long journey that was', 'exclamation', 3),
  ts('How beautifully she sings', 'exclamation', 3),
]

/* ------------------------------------------------------------------ *
 * Questions to rebuild word by word
 *
 * Only one capital letter and only one question mark in each set, so exactly
 * one arrangement can be defended. No word is repeated inside a question,
 * because two identical tiles would look like two right answers.
 * ------------------------------------------------------------------ */

export const QUESTION_ORDERS: { words: string[]; tier: Tier }[] = [
  { words: ['Where', 'is', 'my', 'pencil?'], tier: 1 },
  { words: ['What', 'is', 'your', 'name?'], tier: 1 },
  { words: ['Who', 'took', 'my', 'ruler?'], tier: 1 },
  { words: ['Is', 'this', 'your', 'bag?'], tier: 1 },
  { words: ['Where', 'are', 'the', 'baskets?'], tier: 1 },
  { words: ['Why', 'is', 'the', 'gate', 'locked?'], tier: 2 },
  { words: ['When', 'does', 'the', 'lesson', 'start?'], tier: 2 },
  { words: ['Can', 'you', 'lend', 'me', 'a', 'biro?'], tier: 2 },
  { words: ['Are', 'you', 'coming', 'to', 'school?'], tier: 2 },
  { words: ['Did', 'you', 'finish', 'your', 'work?'], tier: 2 },
  { words: ['How', 'many', 'oranges', 'did', 'she', 'buy?'], tier: 3 },
  { words: ['Whose', 'uniform', 'is', 'on', 'the', 'bench?'], tier: 3 },
]

export const KIND_LABEL: Record<SentenceKind, string> = {
  statement: 'Statement',
  question: 'Question',
  command: 'Command',
  exclamation: 'Exclamation',
}

export const KIND_MARK: Record<SentenceKind, string> = {
  statement: '.',
  question: '?',
  command: '.',
  exclamation: '!',
}

/* ------------------------------------------------------------------ *
 * Question words
 * ------------------------------------------------------------------ */

export const QUESTION_WORD_CLOZE: Cloze[] = [
  cz('____ is your name?', 'What', ['Where', 'When', 'Why'], 1, '"What" asks about a thing or a fact.'),
  cz('____ is my school bag?', 'Where', ['Who', 'What', 'Why'], 1, '"Where" asks about a place.'),
  cz('____ did you come late?', 'Why', ['Who', 'Where', 'What'], 2, '"Why" asks for a reason.'),
  cz('____ took my ruler?', 'Who', ['Where', 'When', 'Why'], 1, '"Who" asks about a person.'),
  cz('____ does the lesson start?', 'When', ['Who', 'What', 'Which'], 2, '"When" asks about a time.'),
  cz('____ many oranges did Ada buy?', 'How', ['What', 'Who', 'Why'], 2, '"How many" asks about a number.'),
  cz('____ one is your bag, the red or the blue?', 'Which', ['Who', 'Why', 'When'], 3, '"Which" asks you to choose from a set.'),
  cz('____ bag is this?', 'Whose', ['Who', 'Why', 'When'], 3, '"Whose" asks who owns something.'),
  cz('____ old are you?', 'How', ['What', 'Who', 'Why'], 1, '"How old" asks about age.'),
  cz('____ are you feeling today?', 'How', ['Who', 'Where', 'Which'], 2, '"How" asks about the way something is.'),
  cz('____ do you live?', 'Where', ['Who', 'Which', 'Whose'], 1, '"Where" asks about a place.'),
  cz('____ is knocking at the door?', 'Who', ['Where', 'When', 'Which'], 1, '"Who" asks about a person.'),
  cz('____ colour is your uniform?', 'What', ['Who', 'Where', 'Why'], 2, '"What colour" asks about a quality.'),
  cz('____ will the rain stop?', 'When', ['Who', 'Which', 'Whose'], 2, '"When" asks about a time.'),
  cz('____ is that boy crying?', 'Why', ['Which', 'Whose', 'Who'], 2, '"Why" asks for a reason.'),
  cz('____ did you put my torch?', 'Where', ['Who', 'Whose', 'Which'], 2, '"Where" asks about a place.'),
  cz('____ is inside the envelope?', 'What', ['Who', 'Where', 'When'], 2, '"What" asks about a thing.'),
  cz('____ sandals are these?', 'Whose', ['Who', 'When', 'Why'], 3, '"Whose" asks who owns something.'),
]

/* ------------------------------------------------------------------ *
 * Prepositions
 * ------------------------------------------------------------------ */

export const PREPOSITION_TIME_CLOZE: Cloze[] = [
  cz('We go to church ____ Sunday.', 'on', ['in', 'at', 'of'], 1, 'Use "on" with days of the week.'),
  cz('My birthday is ____ May.', 'in', ['on', 'at', 'of'], 1, 'Use "in" with months and years.'),
  cz('The lesson starts ____ eight o’clock.', 'at', ['in', 'on', 'of'], 2, 'Use "at" with clock times.'),
  cz('We sleep ____ night.', 'at', ['on', 'to', 'of'], 2, 'We say "at night", never "on night".'),
  cz('It is very hot ____ March.', 'in', ['on', 'at', 'of'], 2, 'Use "in" with months.'),
  cz('The shop opens ____ Monday morning.', 'on', ['in', 'at', 'of'], 2, 'Use "on" with a named day.'),
  cz('The match kicks off ____ four o’clock.', 'at', ['in', 'on', 'of'], 2, 'Use "at" with clock times.'),
  cz('Independence Day is ____ October.', 'in', ['on', 'at', 'of'], 3, 'Use "in" with months.'),
  cz('We travel to the village ____ December.', 'in', ['on', 'at', 'of'], 3, 'Use "in" with months.'),
  cz('The bus leaves ____ Friday afternoon.', 'on', ['in', 'at', 'of'], 3, 'Use "on" with a named day.'),
]

export const PREPOSITION_PLACE_CLOZE: Cloze[] = [
  cz('The fish live ____ the river.', 'in', ['on', 'over', 'beside'], 1, '"In" means inside something.'),
  cz('The mat is ____ the floor.', 'on', ['in', 'under', 'between'], 1, '"On" means resting on top of a surface.'),
  cz('The cat hid ____ the bed, so nobody could see it.', 'under', ['on', 'above', 'across'], 1, '"Under" means below and hidden by something.'),
  cz('There is a big tree ____ our house and the road.', 'between', ['among', 'under', 'over'], 2, '"Between" is used for two things, one on each side.'),
  cz('Musa walked ____ the doorway and came inside.', 'through', ['above', 'beside', 'under'], 2, '"Through" means from one side to the other.'),
  cz('The aeroplane flew ____ the clouds.', 'above', ['under', 'beside', 'between'], 2, '"Above" means higher up than something.'),
  cz('She poured the water ____ the bucket.', 'into', ['above', 'beside', 'between'], 2, '"Into" shows movement to the inside of something.'),
  cz('Ada sat ____ Chidi and Musa.', 'between', ['among', 'under', 'above'], 2, '"Between" is used for two named people or things.'),
  cz('The pencil rolled ____ the table and fell down.', 'off', ['in', 'into', 'among'], 3, '"Off" shows movement away from a surface.'),
  cz('The goats were grazing ____ the tall grass.', 'among', ['between', 'above', 'onto'], 3, '"Among" is used for more than two things.'),
  cz('Put your sandals ____ the bench, not on it.', 'under', ['onto', 'above', 'across'], 2, '"Under" means below something.'),
  cz('The bridge goes ____ the river.', 'across', ['inside', 'beneath', 'among'], 3, '"Across" means from one side to the other.'),
]

/* ------------------------------------------------------------------ *
 * Conjunctions
 *
 * Only frames where the wrong words are grammatically impossible, never
 * merely less likely.
 * ------------------------------------------------------------------ */

export const CONJUNCTION_CLOZE: Cloze[] = [
  cz('Ada bought bread ____ milk.', 'and', ['because', 'so', 'but'], 1, '"And" adds one thing to another.'),
  cz('Chidi stayed at home ____ of the heavy rain.', 'because', ['but', 'so', 'and'], 2, '"Because of" gives the reason for something.'),
  cz('We could not play outside ____ of the mud.', 'because', ['but', 'or', 'and'], 2, '"Because of" gives the reason for something.'),
  cz('Musa washed the plates ____ swept the floor.', 'and', ['because', 'or', 'so'], 1, '"And" joins two things the same person did.'),
  cz('The market was closed ____ of the public holiday.', 'because', ['but', 'so', 'or'], 3, '"Because of" gives the reason for something.'),
  cz('Ngozi packed her books ____ her uniform.', 'and', ['because', 'so', 'but'], 1, '"And" adds one thing to another.'),
  cz('The road was flooded ____ of the storm.', 'because', ['but', 'so', 'and'], 3, '"Because of" gives the reason for something.'),
  cz('Tunde swept the compound ____ fetched the water.', 'and', ['because', 'or', 'so'], 1, '"And" joins two things the same person did.'),
  cz('Halima packed her ruler ____ her sharpener.', 'and', ['because', 'so', 'but'], 1, '"And" adds one thing to another.'),
  cz('The lesson was cancelled ____ of the rain.', 'because', ['but', 'so', 'and'], 2, '"Because of" gives the reason for something.'),
  cz('Bisi could not sleep ____ of the noise.', 'because', ['but', 'or', 'and'], 2, '"Because of" gives the reason for something.'),
  cz('Emeka bought yams, plantains ____ tomatoes.', 'and', ['because', 'so', 'but'], 1, '"And" comes before the last thing in a list.'),
  cz('We waited at the bus stop ____ of the traffic.', 'because', ['but', 'so', 'or'], 3, '"Because of" gives the reason for something.'),
  cz('Sade opened her books ____ her pencil case.', 'and', ['because', 'so', 'but'], 1, '"And" adds one thing to another.'),
  cz('The match was stopped ____ of the storm.', 'because', ['but', 'so', 'or'], 2, '"Because of" gives the reason for something.'),
  cz('Kunle carried the bucket ____ the broom.', 'and', ['because', 'so', 'but'], 1, '"And" adds one thing to another.'),
  cz('The shop was shut ____ of the public holiday.', 'because', ['but', 'so', 'or'], 3, '"Because of" gives the reason for something.'),
  cz('Funke greeted her teacher ____ sat down.', 'and', ['because', 'or', 'so'], 1, '"And" joins two things the same person did.'),
  cz('We travelled at night ____ of the traffic.', 'because', ['but', 'so', 'and'], 3, '"Because of" gives the reason for something.'),
]

export const CONJUNCTION_JOBS: { job: string; answer: string; wrong: string[] }[] = [
  { job: 'gives a REASON for something', answer: 'because', wrong: ['and', 'but', 'or'] },
  { job: 'shows a CHOICE between two things', answer: 'or', wrong: ['and', 'but', 'because'] },
  { job: 'ADDS one idea to another', answer: 'and', wrong: ['but', 'or', 'because'] },
  { job: 'shows two ideas that are OPPOSITE', answer: 'but', wrong: ['and', 'or', 'because'] },
  { job: 'shows the RESULT of something', answer: 'so', wrong: ['and', 'or', 'because'] },
]

/* ------------------------------------------------------------------ *
 * Conjunctions by the job they do
 *
 * The question names the job it wants — contrast, reason, result, choice or
 * addition — so only one joining word can be defended even where a rival word
 * would also make a grammatical sentence.
 * ------------------------------------------------------------------ */

export type ConjunctionSense = 'ADDITION' | 'CONTRAST' | 'REASON' | 'RESULT' | 'CHOICE'

export const SENSE_ASK: Record<ConjunctionSense, string> = {
  ADDITION: 'ADDS a second idea',
  CONTRAST: 'shows a CONTRAST',
  REASON: 'gives the REASON',
  RESULT: 'shows the RESULT',
  CHOICE: 'offers a CHOICE',
}

export const SENSE_JOB: Record<ConjunctionSense, string> = {
  ADDITION: 'It adds one idea to another',
  CONTRAST: 'It shows a contrast between two ideas',
  REASON: 'It gives the reason for something',
  RESULT: 'It shows the result of something',
  CHOICE: 'It offers a choice between two things',
}

export interface SenseCloze {
  text: string
  sense: ConjunctionSense
  answer: string
  wrong: string[]
  tier: Tier
  why: string
}

const sc = (
  text: string, sense: ConjunctionSense, answer: string, wrong: string[], tier: Tier, why: string,
): SenseCloze => ({ text, sense, answer, wrong, tier, why })

export const CONJUNCTION_SENSE: SenseCloze[] = [
  sc('Tunde was tired ____ he kept running.', 'CONTRAST', 'but', ['and', 'or', 'because'], 2, '"But" joins two ideas that pull against each other.'),
  sc('Ada was ill ____ she still came to school.', 'CONTRAST', 'but', ['and', 'or', 'so'], 2, '"But" shows the second idea goes against the first.'),
  sc('The bag was small ____ it was very heavy.', 'CONTRAST', 'but', ['and', 'or', 'because'], 2, '"But" shows the two ideas pull against each other.'),
  sc('Musa shouted ____ nobody heard him.', 'CONTRAST', 'but', ['and', 'or', 'so'], 3, '"But" shows the surprising second idea.'),
  sc('The soup smelled lovely ____ it tasted awful.', 'CONTRAST', 'but', ['and', 'or', 'because'], 3, '"But" shows a contrast between the two ideas.'),
  sc('Ngozi stayed at home ____ she was unwell.', 'REASON', 'because', ['and', 'or', 'but'], 2, '"Because" gives the reason for staying at home.'),
  sc('We fetched water from the well ____ the tap was broken.', 'REASON', 'because', ['and', 'or', 'but'], 3, '"Because" comes in front of the reason.'),
  sc('Chidi ran to school ____ he was late.', 'REASON', 'because', ['and', 'or', 'but'], 2, '"Because" gives the reason for running.'),
  sc('The pupils cheered ____ their team had won.', 'REASON', 'because', ['and', 'or', 'but'], 3, '"Because" tells you why they cheered.'),
  sc('It started to rain, ____ we ran inside.', 'RESULT', 'so', ['and', 'or', 'because'], 2, '"So" shows what happened as a result.'),
  sc('The gate was locked, ____ we waited outside.', 'RESULT', 'so', ['and', 'or', 'because'], 2, '"So" shows the result of the locked gate.'),
  sc('Halima had no money, ____ she walked home.', 'RESULT', 'so', ['and', 'or', 'because'], 3, '"So" shows what happened as a result.'),
  sc('The lorry broke down, ____ the goods arrived late.', 'RESULT', 'so', ['and', 'or', 'because'], 3, '"So" shows the result of the breakdown.'),
  sc('You may have rice ____ beans.', 'CHOICE', 'or', ['and', 'but', 'because'], 1, '"Or" offers a choice between two things.'),
  sc('Shall we walk ____ take a bus?', 'CHOICE', 'or', ['and', 'but', 'because'], 2, '"Or" offers a choice between two plans.'),
  sc('Is your uniform blue ____ green?', 'CHOICE', 'or', ['and', 'but', 'because'], 1, '"Or" offers a choice between two things.'),
  sc('Would you like a mango ____ an orange?', 'CHOICE', 'or', ['and', 'but', 'because'], 1, '"Or" offers a choice between two things.'),
  sc('Bisi swept the floor ____ washed the plates.', 'ADDITION', 'and', ['but', 'or', 'because'], 1, '"And" adds a second thing she did.'),
  sc('Emeka bought yams ____ plantains.', 'ADDITION', 'and', ['but', 'or', 'because'], 1, '"And" adds one thing to another.'),
  sc('The rain fell ____ the wind blew.', 'ADDITION', 'and', ['but', 'or', 'because'], 2, '"And" adds a second idea to the first.'),
  sc('Segun packed his books ____ locked the cupboard.', 'ADDITION', 'and', ['but', 'or', 'because'], 2, '"And" adds a second thing he did.'),
  sc('Funke read the story ____ drew a picture.', 'ADDITION', 'and', ['but', 'or', 'because'], 1, '"And" adds a second thing she did.'),
  sc('You may take one mango ____ one orange, not both.', 'CHOICE', 'or', ['and', 'but', 'because'], 2, '"Not both" tells you it is a choice, so we use "or".'),
  sc('The tap was dry, ____ we could not wash.', 'RESULT', 'so', ['and', 'or', 'because'], 3, '"So" shows what happened as a result.'),
  sc('Kunle forgot his key, ____ he waited outside.', 'RESULT', 'so', ['and', 'or', 'because'], 2, '"So" shows what happened as a result.'),
  sc('Aisha studied hard ____ she passed the test.', 'RESULT', 'so', ['and', 'or', 'but'], 3, '"So" shows the result of studying hard.'),
  sc('The teacher waited ____ the class was noisy.', 'REASON', 'because', ['and', 'or', 'but'], 3, '"Because" comes in front of the reason for waiting.'),
]

/** Finished sentences whose joining word does exactly one identifiable job. */
export interface ConjunctionUse {
  text: string
  word: string
  sense: ConjunctionSense
  tier: Tier
}

const cu = (text: string, word: string, sense: ConjunctionSense, tier: Tier): ConjunctionUse =>
  ({ text, word, sense, tier })

export const CONJUNCTION_USES: ConjunctionUse[] = [
  cu('Tunde was tired but he kept running.', 'but', 'CONTRAST', 2),
  cu('The bag was small but very heavy.', 'but', 'CONTRAST', 2),
  cu('Ada shouted but nobody heard her.', 'but', 'CONTRAST', 2),
  cu('Musa was late but the bus was still waiting.', 'but', 'CONTRAST', 3),
  cu('Ngozi stayed at home because she was unwell.', 'because', 'REASON', 2),
  cu('Chidi ran to school because he was late.', 'because', 'REASON', 2),
  cu('We used the well because the tap was broken.', 'because', 'REASON', 3),
  cu('The pupils cheered because their team had won.', 'because', 'REASON', 3),
  cu('It started to rain, so we ran inside.', 'so', 'RESULT', 2),
  cu('The gate was locked, so we waited outside.', 'so', 'RESULT', 2),
  cu('Halima had no money, so she walked home.', 'so', 'RESULT', 3),
  cu('The lorry broke down, so the goods arrived late.', 'so', 'RESULT', 3),
  cu('You may have rice or beans.', 'or', 'CHOICE', 1),
  cu('Is your uniform blue or green?', 'or', 'CHOICE', 1),
  cu('Shall we walk or take a bus?', 'or', 'CHOICE', 2),
  cu('Bisi swept the floor and washed the plates.', 'and', 'ADDITION', 1),
  cu('Emeka bought yams and plantains.', 'and', 'ADDITION', 1),
  cu('The rain fell and the wind blew.', 'and', 'ADDITION', 2),
  cu('Segun packed his books and locked the cupboard.', 'and', 'ADDITION', 2),
  cu('Funke read the story and drew a picture.', 'and', 'ADDITION', 1),
]

/** Words that are never joining words, for a "tap the conjunctions" board. */
export const NOT_CONJUNCTIONS = [
  'basket', 'quickly', 'under', 'teacher', 'washed', 'happy', 'beside', 'pencil',
  'loudly', 'goat', 'bright', 'carried', 'above', 'bucket', 'gently', 'lorry',
]

/* ------------------------------------------------------------------ *
 * Joining two sentences
 *
 * The distractors are broken sentences, not rival conjunctions, so exactly
 * one option is defensible.
 * ------------------------------------------------------------------ */

export interface JoinItem {
  a: string
  b: string
  joined: string
  wrong: string[]
  tier: Tier
  why: string
}

const jn = (a: string, b: string, joined: string, wrong: string[], tier: Tier, why: string): JoinItem =>
  ({ a, b, joined, wrong, tier, why })

export const JOIN_ITEMS: JoinItem[] = [
  jn(
    'Ada opened the door.', 'Ada went inside.',
    'Ada opened the door and went inside.',
    ['Ada opened the door and Ada went inside and.', 'Ada and opened the door went inside.', 'And Ada opened the door went inside.'],
    1, 'Join with "and" and say the name only once.',
  ),
  jn(
    'Musa was tired.', 'Musa finished his homework.',
    'Musa was tired but he finished his homework.',
    ['Musa was tired but finished but his homework.', 'But Musa was tired he finished his homework.', 'Musa but was tired he finished his homework.'],
    2, '"But" joins two ideas that pull against each other.',
  ),
  jn(
    'It started to rain.', 'We ran inside.',
    'It started to rain, so we ran inside.',
    ['It started to rain so, we ran inside so.', 'So it started to rain we ran inside.', 'It so started to rain we ran inside.'],
    2, '"So" shows what happened as a result.',
  ),
  jn(
    'Ngozi was late.', 'Ngozi missed the bus.',
    'Ngozi was late because she missed the bus.',
    ['Ngozi was late because missed the bus because.', 'Because Ngozi was late she missed the bus because.', 'Ngozi because was late she missed the bus.'],
    2, '"Because" gives the reason, and it goes in front of the reason.',
  ),
  jn(
    'Chidi swept the floor.', 'Chidi washed the plates.',
    'Chidi swept the floor and washed the plates.',
    ['Chidi swept the floor and and washed the plates.', 'And Chidi swept the floor washed the plates.', 'Chidi swept and the floor washed the plates.'],
    1, 'Join with "and" and say the name only once.',
  ),
  jn(
    'The bag was small.', 'The bag was very heavy.',
    'The bag was small but very heavy.',
    ['The bag was small but but very heavy.', 'But the bag was small very heavy.', 'The bag but was small very heavy.'],
    2, '"But" joins two ideas that pull against each other.',
  ),
  jn(
    'Halima finished her work.', 'Halima went out to play.',
    'Halima finished her work and went out to play.',
    ['Halima finished her work and and went out to play.', 'And Halima finished her work went out to play.', 'Halima and finished her work went out to play.'],
    1, 'Join with "and" and say the name only once.',
  ),
  jn(
    'The tap was broken.', 'We fetched water from the well.',
    'The tap was broken, so we fetched water from the well.',
    ['The tap was broken so, we fetched so water from the well.', 'So the tap was broken we fetched water from the well so.', 'The tap so was broken we fetched water from the well.'],
    3, '"So" shows what happened as a result.',
  ),
  jn(
    'Emeka missed the lesson.', 'Emeka was ill.',
    'Emeka missed the lesson because he was ill.',
    ['Emeka missed the lesson because was ill because.', 'Because Emeka missed the lesson he was ill because.', 'Emeka because missed the lesson he was ill.'],
    2, '"Because" gives the reason, and it goes in front of the reason.',
  ),
  jn(
    'Bisi packed her books.', 'Bisi locked the cupboard.',
    'Bisi packed her books and locked the cupboard.',
    ['Bisi packed her books and and locked the cupboard.', 'And Bisi packed her books locked the cupboard.', 'Bisi and packed her books locked the cupboard.'],
    2, 'Join with "and" and say the name only once.',
  ),
]

/* ------------------------------------------------------------------ *
 * Commonly confused words
 * ------------------------------------------------------------------ */

export const CONFUSABLE_CLOZE: Cloze[] = [
  cz('The dog wagged ____ tail.', 'its', ["it's", "its'", 'it is'], 2, '"Its" shows owning. "It’s" is short for "it is".'),
  cz('____ raining outside.', "It's", ['Its', "Its'", 'It'], 2, '"It’s" is short for "it is". Read it back the long way to check.'),
  cz('The girls put on ____ uniforms.', 'their', ['there', "they're", 'theirs'], 2, '"Their" shows owning; "there" is a place.'),
  cz('____ going to be late.', "They're", ['Their', 'There', 'Theirs'], 3, '"They’re" is short for "they are".'),
  cz('Put the basket over ____.', 'there', ['their', "they're", 'theirs'], 2, '"There" tells you a place.'),
  cz('Is this ____ pencil?', 'your', ["you're", 'yours', "your's"], 2, '"Your" shows owning. "You’re" is short for "you are".'),
  cz('____ very kind to help me.', "You're", ['Your', 'Yours', "Your's"], 3, '"You’re" is short for "you are".'),
  cz('Ada went ____ the market.', 'to', ['too', 'two', 'tow'], 1, '"To" shows where you are going.'),
  cz('The soup is ____ hot to eat.', 'too', ['to', 'two', 'tow'], 2, '"Too" means more than you want.'),
  cz('I bought ____ oranges.', 'two', ['to', 'too', 'tow'], 1, '"Two" is the number 2.'),
  cz('____ textbook is this?', 'Whose', ["Who's", 'Whos', 'Whoes'], 3, '"Whose" asks who owns it. "Who’s" means "who is".'),
  cz('____ at the door?', "Who's", ['Whose', 'Whos', 'Whoes'], 3, '"Who’s" is short for "who is".'),
  cz('We must ____ our spellings every day.', 'practise', ['practice', 'practises', 'practising'], 3, 'The verb is "practise" with an s; the noun is "practice" with a c.'),
  cz('Football ____ is on Friday.', 'practice', ['practise', 'practises', 'practising'], 3, 'The noun is "practice" with a c; the verb is "practise" with an s.'),
  cz('The soup was ____ good.', 'quite', ['quiet', 'quit', 'quitely'], 3, '"Quite" means fairly; "quiet" means not noisy.'),
  cz('Please be ____ in the library.', 'quiet', ['quite', 'quit', 'quietly'], 3, '"Quiet" means not noisy.'),
  cz('Come and sit ____.', 'here', ['hear', 'heres', 'hears'], 2, '"Here" is a place; "hear" is what you do with your ears.'),
  cz('Did you ____ that noise?', 'hear', ['here', 'heres', 'hears'], 2, '"Hear" has "ear" inside it.'),
  cz('Chidi fell ____ his bicycle.', 'off', ['of', 'ofe', 'offe'], 2, '"Off" means away from something.'),
  cz('She drank a cup ____ tea.', 'of', ['off', 'ove', 'offe'], 2, '"Of" links two things; "off" means away from.'),
  cz('This bag is heavier ____ that one.', 'than', ['then', 'that', 'them'], 3, '"Than" is used when you compare two things.'),
  cz('First we ate, ____ we washed the plates.', 'then', ['than', 'that', 'them'], 3, '"Then" tells you what happened next.'),
  cz('____ teacher is very kind.', 'Our', ['Are', 'Hour', 'Ours'], 2, '"Our" shows that something belongs to us.'),
  cz('The children ____ playing outside.', 'are', ['our', 'is', 'am'], 2, '"Are" goes with more than one person.'),
  cz('Do not ____ your pencil.', 'lose', ['loose', 'loosen', 'looses'], 3, '"Lose" means you cannot find it; "loose" means not tight.'),
  cz('We ____ in the same class last year.', 'were', ["we're", 'where', 'wear'], 3, '"Were" is the past of "are".'),
  cz('____ is my ruler?', 'Where', ['Were', "We're", 'Wear'], 2, '"Where" asks about a place.'),
  cz('Ada could not find ____ shoes.', 'her', ['hers', "her's", 'she'], 2, '"Her" comes before the thing owned; "hers" stands alone.'),
  cz('That blue bag is ____.', 'mine', ["mine's", 'my', "my's"], 2, '"Mine" stands on its own; "my" comes before a noun.'),
  cz('The goat broke ____ rope.', 'its', ["it's", "its'", 'it is'], 2, '"Its" shows owning and never takes an apostrophe.'),
  cz('____ almost time for the lesson.', "It's", ['Its', "Its'", 'It'], 3, 'Read it back: "it is almost time", so it needs "It’s".'),
  cz('The traders packed ____ baskets.', 'their', ['there', "they're", 'theirs'], 2, '"Their" shows owning.'),
  cz('I left my torch over ____ by the gate.', 'there', ['their', "they're", 'theirs'], 2, '"There" tells you a place.'),
  cz('____ the fastest runner in the class.', "You're", ['Your', 'Yours', "Your's"], 3, 'Read it back: "you are the fastest".'),
  cz('Bring ____ own pencil to the test.', 'your', ["you're", 'yours', "your's"], 2, '"Your" shows owning.'),
  cz('We walked ____ far and got tired.', 'too', ['to', 'two', 'tow'], 2, '"Too" means more than you want.'),
  cz('Musa scored ____ goals on Saturday.', 'two', ['to', 'too', 'tow'], 1, '"Two" is the number 2.'),
  cz('Give the letter ____ the headmaster.', 'to', ['too', 'two', 'tow'], 1, '"To" shows who receives something.'),
  cz('____ turn is it to sweep?', 'Whose', ["Who's", 'Whos', 'Whoes'], 3, '"Whose" asks who owns it or whose turn it is.'),
  cz('Do you know ____ coming to the party?', "who's", ['whose', 'whos', 'whoes'], 3, 'Read it back: "who is coming".'),
  cz('Ngozi must ____ the piano every evening.', 'practise', ['practice', 'practises', 'practising'], 3, 'The verb is "practise" with an s.'),
  cz('Choir ____ starts at four.', 'practice', ['practise', 'practises', 'practising'], 3, 'The noun is "practice" with a c.'),
  cz('The classroom was ____ full.', 'quite', ['quiet', 'quit', 'quitely'], 3, '"Quite" means fairly.'),
  cz('The baby is asleep, so keep ____.', 'quiet', ['quite', 'quit', 'quietly'], 3, '"Quiet" means not noisy.'),
  cz('Can you ____ the drums from the compound?', 'hear', ['here', 'heres', 'hears'], 2, '"Hear" has "ear" inside it.'),
  cz('Put the bucket down ____.', 'here', ['hear', 'heres', 'hears'], 2, '"Here" is a place.'),
  cz('Take your sandals ____ before you come in.', 'off', ['of', 'ofe', 'offe'], 2, '"Off" means away from something.'),
  cz('She ate a plate ____ rice.', 'of', ['off', 'ove', 'offe'], 2, '"Of" links two things.'),
  cz('My bag is lighter ____ yours.', 'than', ['then', 'that', 'them'], 3, '"Than" is used when you compare.'),
  cz('We swept the floor and ____ we mopped it.', 'then', ['than', 'that', 'them'], 3, '"Then" tells you what happened next.'),
  cz('____ school is beside the market.', 'Our', ['Are', 'Hour', 'Ours'], 2, '"Our" shows that it belongs to us.'),
  cz('Where ____ my shoes?', 'are', ['our', 'is', 'am'], 2, '"Shoes" is plural, so it takes "are".'),
  cz('Tie the rope tightly so it is not ____.', 'loose', ['lose', 'loses', 'losing'], 3, '"Loose" means not tight; "lose" means cannot find.'),
  cz('The gates ____ locked when we arrived.', 'were', ["we're", 'where', 'wear'], 3, '"Were" is the past of "are".'),
  cz('____ did you buy that torch?', 'Where', ['Were', "We're", 'Wear'], 2, '"Where" asks about a place.'),
  cz('What will you ____ to the party?', 'wear', ['where', 'were', "we're"], 3, '"Wear" is what you do with clothes.'),
]

/* ------------------------------------------------------------------ *
 * Direct speech
 * ------------------------------------------------------------------ */

export interface Quote {
  speaker: string
  verb: string
  said: string
  /**
   * The mark that closes the spoken words, *inside* the speech marks. A
   * question keeps its question mark there — "Where is my biro." would be
   * plain wrong, however tidy it looks.
   */
  mark: '.' | '?' | '!'
  tier: Tier
}

const q = (speaker: string, verb: string, said: string, tier: Tier, mark: '.' | '?' | '!' = '.'): Quote =>
  ({ speaker, verb, said, mark, tier })

export const QUOTES: Quote[] = [
  q('Ada', 'said', 'I am hungry', 1),
  q('Musa', 'shouted', 'Wait for me', 1),
  q('The teacher', 'said', 'Open your textbooks', 2),
  q('Chidi', 'asked', 'Where is my biro', 2, '?'),
  q('Ngozi', 'whispered', 'The baby is sleeping', 2),
  q('Mother', 'called', 'Come and eat', 1),
  q('Halima', 'said', 'I finished my homework', 2),
  q('The driver', 'shouted', 'The bus is leaving', 3),
  q('Emeka', 'replied', 'I do not know', 2),
  q('Bisi', 'said', 'This mango is sweet', 1),
  q('Father', 'said', 'We are travelling to Enugu', 3),
  q('Segun', 'asked', 'May I borrow your ruler', 3, '?'),
  q('The nurse', 'said', 'Wash your hands', 2),
  q('Funke', 'laughed', 'That was very funny', 3),
  q('Yusuf', 'said', 'The gate is locked', 2),
  q('Amaka', 'asked', 'When does the match start', 2, '?'),
  q('The driver', 'asked', 'Where are you going', 3, '?'),
]
