/**
 * Writes CONTENT-NG.md, CONTENT-UK.md and CONTENT-US.md.
 *
 * Only the measured part is generated — everything between the coverage
 * markers. The notes, the changelog and the plan around them are written by
 * hand and preserved, because a file that regenerates wholesale stops being
 * somewhere anyone records a decision.
 *
 * Run `npm run content:track` after adding skills. The counts then cannot
 * drift from the pack, which is the whole point: the last time coverage was
 * described from memory it was wrong by a factor of four.
 */

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { registerAllCurricula } from '../src/content'
import { listCurricula } from '../src/engine/registry'
import type { CurriculumDef, SkillDef, SubjectDef } from '../src/engine/types'

registerAllCurricula()

const START = '<!-- coverage:start -->'
const END = '<!-- coverage:end -->'

const FILES: Record<string, string> = {
  'ng-ube': 'CONTENT-NG.md',
  'uk-nc': 'CONTENT-UK.md',
  'us-ccss': 'CONTENT-US.md',
}

const skillsOf = (subject: SubjectDef): SkillDef[] =>
  (subject.strands ?? []).flatMap((s) => s.skills ?? [])

function coverageFor(c: CurriculumDef): string {
  const bands = c.yearBands
  const live = c.subjects.filter((s) => s.available)
  const planned = c.subjects.filter((s) => !s.available)
  const out: string[] = []

  const count = (subject: SubjectDef, band: string) =>
    skillsOf(subject).filter((s) => s.yearBand === band).length

  /* Subject x class, the table that shows where the holes are. */
  out.push(`| Subject | ${bands.map((b) => b.short).join(' | ')} | Total |`)
  out.push(`|---|${bands.map(() => '--:').join('|')}|--:|`)

  let grand = 0
  for (const subject of live) {
    const cells = bands.map((b) => count(subject, b.id))
    const total = cells.reduce((a, x) => a + x, 0)
    grand += total
    out.push(`| **${subject.name}** | ${cells.map((n) => (n === 0 ? '—' : n)).join(' | ')} | **${total}** |`)
  }
  const perBand = bands.map((b) => live.reduce((a, s) => a + count(s, b.id), 0))
  out.push(`| **All** | ${perBand.map((n) => (n === 0 ? '—' : `**${n}**`)).join(' | ')} | **${grand}** |`)

  out.push('')
  out.push(`**${grand} skills** across ${live.length} authored subject${live.length === 1 ? '' : 's'}.`)

  /* Empty classes are the thing worth naming outright. */
  const empty = bands.filter((b, i) => perBand[i] === 0)
  if (empty.length) {
    out.push('')
    out.push(
      `> **${empty.length} of ${bands.length} classes have nothing at all:** ${empty.map((b) => b.label).join(', ')}.`,
    )
  }

  if (planned.length) {
    out.push('')
    out.push('### Declared, not yet authored')
    out.push('')
    out.push(planned.map((s) => `${s.icon} ${s.name}`).join(' · '))
    out.push('')
    out.push(
      'These show as locked rather than empty, so a child never opens a subject with nothing in it.',
    )
  }

  /* The full list, so a gap can be seen rather than counted. */
  for (const subject of live) {
    out.push('')
    out.push(`### ${subject.icon} ${subject.name} — skill by skill`)
    for (const band of bands) {
      const here = skillsOf(subject).filter((s) => s.yearBand === band.id)
      out.push('')
      out.push(`**${band.label}** (${here.length})`)
      out.push('')
      out.push(here.length ? here.map((s) => `- ${s.title}`).join('\n') : '- _nothing yet_')
    }
  }

  return out.join('\n')
}

/*
 * The repository root, not the bundle's. This entry is bundled into
 * node_modules/.cache before it runs, so `import.meta.dirname` points there
 * and the first attempt wrote three tracker files into the cache directory.
 */
const root = process.cwd()
const today = new Date().toISOString().slice(0, 10)

for (const c of listCurricula()) {
  const file = FILES[c.id]
  if (!file) continue
  const full = path.join(root, file)

  const body = [
    START,
    '',
    `_Generated by \`npm run content:track\` on ${today}. Do not edit between the markers._`,
    '',
    coverageFor(c),
    '',
    END,
  ].join('\n')

  let existing = ''
  try {
    existing = await readFile(full, 'utf8')
  } catch {
    existing = ''
  }

  if (existing.includes(START) && existing.includes(END)) {
    const before = existing.slice(0, existing.indexOf(START))
    const after = existing.slice(existing.indexOf(END) + END.length)
    await writeFile(full, before + body + after, 'utf8')
    console.log(`updated ${file} (kept the hand-written parts)`)
  } else {
    await writeFile(full, `${existing.trimEnd()}\n\n${body}\n`, 'utf8')
    console.log(`wrote ${file}`)
  }
}
